name: fire
description: Firebase firestore API.
version: 3.0.0
publish_to: "none"
homepage: https://github.com/RagehAz/fire.git
# --------------------------------------------------------------------------------
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  # ------------------------------------
  basics:
#    path: D:/projects/packages/basics
    git:
      url: https://github.com/RagehAz/basics.git
  # ------------------------------------
  firedart: ^0.9.7
  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  firebase_auth: ^4.9.0
  flutter_facebook_auth: ^6.0.3
  google_sign_in: ^6.1.5
  googleapis_auth: ^1.4.1
  sign_in_with_apple: ^5.0.0
  firebase_storage: ^11.2.6
  firebase_database: ^10.2.5
  firebase_ui_oauth_facebook: ^1.0.24
  firebase_ui_oauth_apple: ^1.0.24
  firebase_ui_oauth_google: ^1.0.21
  firebase_ui_auth: ^1.1.17
  firebase_dart: ^1.0.11

  # FIRE PACKS IN BASICS
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  http: ^1.1.0

#dependency_overrides:
#  intl: ^0.18.1
# --------------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
# --------------------------------------------------------------------------------
flutter:
# --------------------------------------------------------------------------------
