name: fire
description: Firebase firestore API.
version: 0.0.3
publish_to: "none"
homepage: https://github.com/RagehAz/fire.git
# --------------------------------------------------------------------------------
environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
# ------------------------------------
  cloud_firestore: ^4.0.3
  firebase_core: ^2.1.1
  mapper:
    git:
      url: https://github.com/RagehAz/mapper.git
# --------------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
# --------------------------------------------------------------------------------
flutter:
# --------------------------------------------------------------------------------
