name: fire
description: Firebase firestore API.
version: 2.0.9
publish_to: "none"
homepage: https://github.com/RagehAz/fire.git
# --------------------------------------------------------------------------------
environment:
  sdk: '>=2.19.6 <4.0.0' # nour's recommendation ">=3.0.0 < 4.0.0"
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  # ------------------------------------
  basics:
#    path: D:/projects/packages/helpers/basics
    git:
      url: https://github.com/RagehAz/basics.git
  # ------------------------------------
  cloud_firestore: ^4.8.1
  firebase_core: ^2.14.0
  firedart: ^0.9.5
  firebase_dart: ^1.0.7
  extension_google_sign_in_as_googleapis_auth: ^2.0.10
  firebase_auth: ^4.7.0
  flutter_facebook_auth: ^5.0.11
  google_sign_in: ^6.1.4
  googleapis_auth: ^1.4.1
  sign_in_with_apple: ^5.0.0
  http: ^0.13.6
  firebase_storage: ^11.2.3
  firebase_database: ^10.2.3
# ------------------------------------
#  firebase_ui_oauth_facebook: ^1.0.24
#  firebase_ui_oauth_apple: ^1.0.24
#  firebase_ui_oauth_google: ^1.0.21
#  firebase_ui_auth: ^1.1.17
# --------------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
# --------------------------------------------------------------------------------
flutter:
# --------------------------------------------------------------------------------
