name: fire
description: Firebase firestore API.
version: 4.8.0
publish_to: "none"
homepage: https://github.com/RagehAz/fire.git
# --------------------------------------------------------------------------------
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  # ------------------------------------
  basics:
    # ----------------
    # IOS
#    path: /Users/rageh/projects/bldrs/basics
    # ----------------
    # ANDROID
#    path: D:/projects/bldrs_packs/basics
    # ----------------
    # GIT
    git:
      url: https://github.com/RagehAz/basics.git
  # ------------------------------------

  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  flutter_facebook_auth: ^6.0.3
  google_sign_in: ^6.2.1
  googleapis_auth: ^1.6.0
  sign_in_with_apple: ^6.1.0

  firebase_core: ^2.25.4

  firebase_ui_auth: ^1.14.0
  firebase_ui_oauth_facebook: ^1.2.20
  firebase_ui_oauth_apple: ^1.2.20
  firebase_ui_oauth_google: ^1.3.2
  firebase_auth: ^4.17.5
  firebase_database: ^10.5.7
  firebase_storage: ^11.7.7

  # FIRE PACKS IN BASICS
  cloud_firestore: ^4.17.5
  http: ^1.2.1

# --------------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
# --------------------------------------------------------------------------------
flutter:
# --------------------------------------------------------------------------------
