name: fire
description: Firebase firestore API.
version: 5.3.0
publish_to: "none"
homepage: https://github.com/RagehAz/fire.git
# --------------------------------------------------------------------------------
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  # ------------------------------------
  basics:
    # -----------------
    # IOS
#    path: /Users/rageh/projects/bldrs/basics
    # ----------------
    # ANDROID
#    path: D:/projects/bldrs_packs/basics
    # ----------------
    # GIT
    git:
      url: https://github.com/RagehAz/basics.git
  # ------------------------------------
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  flutter_facebook_auth: ^6.2.0
  google_sign_in: ^6.2.1
  googleapis_auth: ^1.6.0
  sign_in_with_apple: ^6.1.2
  firebase_core: ^3.5.0
  firebase_ui_auth: ^1.15.0
  firebase_ui_oauth_facebook: ^1.2.21
  firebase_ui_oauth_apple: ^1.2.21
  firebase_ui_oauth_google: ^1.3.3
  firebase_auth: ^5.3.0
  firebase_database: ^11.1.3
  firebase_storage: ^12.3.1
# --------------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
# --------------------------------------------------------------------------------
flutter:
# --------------------------------------------------------------------------------
